version: "3"
services:

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: banco
      POSTGRES_DB: fourfood
    ports:
      - 5432:5432

volumes:
    postgres_data: {}

    
